spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        default-profile: production
        default-label: latest
        native:
          search-locations: file:///${user.home}/dev/config-repo/{application}/{profile}/{label}
server:
  port: 8888