spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/muerciak/config-repo
          uri: file://${user.home}/dev/config-repo/ #/{application}/{profile}/{label}
          searchPaths: '{application}/{profile}/{label}/'

server:
  port: 8888